steps:
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['ci']
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'build']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/air-traffic-expert-portal', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/air-traffic-expert-portal']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'air-traffic-expert-portal'
      - '--image'
      - 'gcr.io/$PROJECT_ID/air-traffic-expert-portal'
      - '--region'
      - 'us-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
